Fix compiling with Qt5 without OpenSSL
Qt 5.3 added a the macro QT_NO_SSL that indicates whether any SSL
support is available, not necessarily OpenSSL. The QT_NO_OPENSSL macro
still exists but its meaning is changed to indicate whether OpenSSL is
available, not any SSL support.

See https://gitlab.com/pteam/korvins-qtbase/commit/b328e36e41dc0c529c897fe845c53be1d39424be.

This fixes the following error compiling with the official Qt5 Mac
installer:

    qRestAPI_p.cpp:102:21: error: no member named 'onSslErrors' in 'qRestAPIPrivate'
        case 5: _t->onSslErrors((*reinterpret_cast<
        QNetworkReply*(*)>(_a[1])),(*reinterpret_cast< const
        QList<QSslError>(*)>(_a[2]))); break;